name: test-build-publish

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test, Build, Publish
    environment: dev
    outputs:
      dev-tag: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=dev-${sha}-${ts}" >> $GITHUB_OUTPUT
      - name: Import secrets
        uses: hashicorp/vault-action@v2.8.0
        id: secrets
        with:
          url: https://vault.maersk-digital.net
          tlsSkipVerify: false
          exportEnv: false
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            telemetry-kv/data/readable/harbor/mop-write-user PASSWORD;
            telemetry-kv/data/readable/harbor/mop-write-user USERNAME;
      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6
      - name: Login to harbor
        run: |
          ko login harbor.maersk.io -u ${{ steps.secrets.outputs.USERNAME }} -p ${{ steps.secrets.outputs.PASSWORD }}
      - name: Build and Push Dev Image
        run: |
          export KO_DOCKER_REPO=harbor.maersk.io/mop/osctrl-tls
          ko build ./tls -t ${{ steps.prep.outputs.BUILD_ID }} --bare --platform=linux/amd64,linux/arm64