name: test-build-publish

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test, Build, Publish
    environment: dev
    strategy:
      matrix:
        components: [tls, admin, api, cli]
    outputs:
      dev-tag: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=dev-${sha}-${ts}" >> $GITHUB_OUTPUT
      - name: Import secrets
        uses: hashicorp/vault-action@v2.8.0
        id: secrets
        with:
          url: https://vault.maersk-digital.net
          tlsSkipVerify: false
          exportEnv: false
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            telemetry-kv/data/readable/harbor/mop-write-user PASSWORD;
            telemetry-kv/data/readable/harbor/mop-write-user USERNAME;
      - name: Build docker image
        uses: ./.github/actions/build/docker
        with:
          osctrl_component: ${{ matrix.components }}
          build_id: ${{ steps.prep.outputs.BUILD_ID }}
          cr_username: ${{ steps.secrets.outputs.USERNAME }}
          cr_access_token: ${{ steps.secrets.outputs.PASSWORD }}
