name: test-build-publish

on:
  push:
    branches:
      - main

env:
  GOLANG_VERSION: 1.23.0
  OSQUERY_VERSION: 5.13.1

jobs:
  build-prep:
    runs-on: ubuntu-latest
    name: Prepare for building images
    environment: dev
    outputs:
      dev-tag: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Generate build ID
        id: prep
        run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=dev-${sha}-${ts}" >> $GITHUB_OUTPUT
  build:
    needs: build-prep
    runs-on: ubuntu-latest
    name: Build docker images
    environment: dev
    strategy:
      matrix:
        components: [tls, api, cli]
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Import secrets
        uses: hashicorp/vault-action@v2.8.0
        id: secrets
        with:
          url: https://vault.maersk-digital.net
          tlsSkipVerify: false
          exportEnv: false
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            telemetry-kv/data/readable/harbor/mop-write-user PASSWORD;
            telemetry-kv/data/readable/harbor/mop-write-user USERNAME;
      - name: Build docker image
        uses: ./.github/actions/build/ko-build
        with:
          osctrl_component: ${{ matrix.components }}
          build_id: ${{needs.build-prep.outputs.dev-tag}}
          cr_username: ${{ steps.secrets.outputs.USERNAME }}
          cr_access_token: ${{ steps.secrets.outputs.PASSWORD }}
          cr_name: harbor.maersk.io
          cr_repo: mop
